### ISSUE TITLE
Please submit for inclusion at Saltstack Formula's organization

### ISSUE THREAD

**Issue by khaije1** [ssplatt/infratest-formula#1]
https://github.com/saltstack-formulas

It'd make it a little simpler for people to get and use this formula.

Cheers and thanks for the good work!

**Comment by ssplatt** [comment]
Hi,

What is the protocol for submitting for inclusion?

Thanks.

**Comment by khaije1** [comment]
With infratest now shipping as part of Saltstack there's less need on my part for this change.
